/* Generated by vala-dbus-binding-tool 0.3.3. Do not modify! */
/* Generated with: vala-dbus-binding-tool --gdbus --directory=. */
using GLib;

namespace org {

	namespace openobex {

		[DBus (name = "org.openobex.Client", timeout = 120000)]
		public interface ObexClient : GLib.Object {

			public abstract async void send_files(GLib.HashTable<string, GLib.Variant> param0, string[] param1, GLib.ObjectPath param2) throws IOError;

			public abstract void pull_business_card(GLib.HashTable<string, GLib.Variant> param0, string param1) throws IOError;

			public abstract void exchange_business_cards(GLib.HashTable<string, GLib.Variant> param0, string param1, string param2) throws IOError;

			public abstract GLib.ObjectPath create_session(GLib.HashTable<string, GLib.Variant> param0) throws IOError;

			public abstract void remove_session(GLib.ObjectPath param0) throws IOError;

			public abstract string get_capabilities(GLib.HashTable<string, GLib.Variant> param0) throws IOError;
		}

	}

		[DBus (name = "org.openobex.Transfer", timeout = 120000)]
		public interface ObexTransfer : GLib.Object {

				[DBus (name = "GetProperties")]
				public abstract GLib.HashTable<string, GLib.Variant> get_properties_() throws IOError;

				public abstract void cancel() throws IOError;
		}

 
	
}
